### PR TITLE
Game logic

### PR DESCRIPTION
**Pull request by Azeem838**
This pull request contains code for the game logic which is contained in the 'gsme_logic.rb' file and called in 'main.rb'.

NOTE: Please run `gem install daru` in your terminal as this project requires the Daru gem

Thank you.

### CODE REVIEW

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello! Good work on your project! however you are missing a few key things. 🎓 

## Changes required 🔴 

- [ ] Please remember to move your logic to the lib folder. Right now everything is functional you should not have an empty lib folder by now. 

- [ ] Right now everything is inside your game_logic.rb try to separate for example the player logic. Onto it's own class/file

- [ ] There is a png file on your project branch that I find it's not used or referenced anywhere. Either use it on your README (I assume it's for that) Or remove it. 

Other than this details you made a great job. 

## Optional changes 

- [ ] I would find a way to remove the letters and numbers above and to the side of your game-board since they are not used. And confuse the player.

Cheers!

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team!
### You have done a good job so far :clap: However, you have an error to solve before the application can be approved.
- [ ] I cannot run the program to test its functionalities when loading a file in ruby, use the generic way using `require_relative` solve this and resubmit for another code review.
cant load

- Happy coding!

By Raymond
slack @iamraymond

**Comment by Azeem838** [comment]
> Hello Team!
> 
> ### You have done a good job so far  However, you have an error to solve before the application can be approved.
> * [ ]  I cannot run the program to test its functionalities when loading a file in ruby, use the generic way using `require_relative` solve this and resubmit for another code review.
>   cant load
> * Happy coding!
> 
> By Raymond
> slack @IAmRaymond

**Comment by Azeem838** [comment]
###################################
Please remember to install the Ruby Gem by running `gem install daru`
##################################

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### Good job so far and for making changes from the previous reviews :clap: Your project has been approved. Congratulations :boom: :100:
### You can merge and submit a project completion form from the dashboard. Good luck with the next milestone.

### NOTE: You can direct a player which value to enter example, (1...9) and also when the game ends, you can ask a player to either continue playing or quit the game. 

- Happy coding!

**Pull request merged**
